# permissions for end users to edit runesservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: runesservice-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gcp-operator-test
    app.kubernetes.io/part-of: gcp-operator-test
    app.kubernetes.io/managed-by: kustomize
  name: runesservice-editor-role
rules:
- apiGroups:
  - runes.bancognb.com.py
  resources:
  - runesservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runes.bancognb.com.py
  resources:
  - runesservices/status
  verbs:
  - get
